version: '3.9'
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab-internship
    hostname: gitlab.internship
    restart: unless-stopped
    ports:
      - ${GITLAB_PORT}:80
    volumes:
      - $GITLAB_DATA/config:/etc/gitlab
      - $GITLAB_DATA/logs:/var/log/gitlab
      - $GITLAB_DATA/data:/var/opt/gitlab
    shm_size: 256m

  gitlab-runner-build-stage:
    image: gitlab/gitlab-runner
    restart: unless-stopped
    container_name: gitlab-runner-build-stage-internship
    volumes:
      - $GITLAB_RUNNER_DATA/srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres
    hostname: postgres.internship
    restart: unless-stopped
    container_name: postgres-internship
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - $POSTGRES_HOST_VOLUME:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-internship
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ${PGADMIN_HOST_VOLUME}:/var/lib/pgadmin

  internship-service:
    image: internship-service
    container_name: internship-service
    restart: unless-stopped
    ports:
      - ${INTERNSHIP_SERVICE_PORT}:8080
    depends_on:
      - postgres
