CREATE schema internship;

CREATE TABLE internship.user (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar UNIQUE NOT NULL,
    email varchar UNIQUE NOT NULL,
    phone_number varchar UNIQUE NOT NULL,
    username varchar UNIQUE NOT NULL,
    telegram_id varchar UNIQUE NOT NULL,
    info varchar NOT NULL,
    date_of_birth date NOT NULL,
    city varchar NOT NULL,
    edu_status varchar,
    university varchar,
    faculty varchar,
    speciality varchar,
    course int,
    status varchar,
    password varchar NOT NULL
);

CREATE TABLE internship.role (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar UNIQUE NOT NULL
);

CREATE TABLE internship.internship (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar UNIQUE NOT NULL,
    description varchar,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    applications_deadline timestamp NOT NULL,
    status varchar NOT NULL
);

CREATE TABLE internship.message (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id int REFERENCES internship.user(id),
    consumer_id int REFERENCES internship.user(id),
    message varchar,
    on_moment timestamp NOT NULL
);

CREATE TABLE internship.user_roles (
    user_id int REFERENCES internship.user(id),
    role_id int REFERENCES internship.role(id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE internship.user_internships (
    user_id int REFERENCES internship.user(id),
    internship_id int REFERENCES internship.internship(id),
    PRIMARY KEY (user_id, internship_id)
);

CREATE TABLE internship.lesson (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    internship_id int REFERENCES internship.internship(id),
    name varchar NOT NULL
);

CREATE TABLE internship.task (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    repo varchar NOT NULL,
    lesson_id int REFERENCES internship.lesson(id)
);

CREATE TABLE internship.user_tasks (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id int REFERENCES internship.user(id),
    task_id int REFERENCES internship.task(id),
    status varchar,
    comment varchar,
    on_moment timestamp NOT NULL
);






