alter table internship.user
drop COLUMN status;

alter table internship.user_internships
add column status varchar;

alter table internship.user_internships
drop constraint user_internships_pkey;

alter table internship.user_internships
add column id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
